name: Bug Report
description: Create a report to help us improve.
title: "Bug: "
type: "bug"
assignees: [""]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you are experiencing.
  
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: List the steps to reproduce the behavior.
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen.

  - type: markdown
    attributes:
      value: |
        ### Screenshots
        <!--If applicable, add screenshots to help explain your problem. Otherwise, remove this section.-->

  - type: input
    id: screenshots
    attributes:
      label: Screenshots
      description: Add any screenshots to help explain your problem.
      placeholder: You can paste image URLs here.

  - type: markdown
    attributes:
      value: |
        ### Desktop (please complete the following information):
        - OS: [e.g. iOS]
        - OS Version: [e.g. 4.0]
        - Ringer Version: [e.g 5.0]

  - type: input
    id: desktop-info
    attributes:
      label: Desktop Information
      description: Provide details about your desktop environment.
      placeholder: List your OS, OS Version, and Ringer Version.

  - type: markdown
    attributes:
      value: |
        ### Additional context
        <!--Add any other context about the problem here. Otherwise, remove this section-->

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem.
      placeholder: Add any additional context about the issue.
