name: Enhancement
description: Suggest an idea for this project.
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the problem is.
      placeholder: Describe the problem you are having.
    validations:
      required: true