# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'ringermobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static

  # Add any other dependencies specific to your project

end
